name: 'OpenAPI JS Client Generator'
description: 'Generates and publishes a package and documentation from a source openapi.yaml file.'
author: 'Oliver Dudgeon'

inputs:
  API_NAME:
    description: 'Name of the API'
    required: true
  GITLAB_API:
    description: 'GitLab API endpoint'
    required: false
    default: https://gitlab.com/api/v4/projects
  GITLAB_API_TOKEN:
    description: 'Token for the GitLab API'
    required: true
  GITLAB_PROJECT:
    description: 'GitLab project from which to get the OpenAPI file'
    required: true
  OPENAPI_FILE:
    description: 'Name of the OpenAPI file'
    required: false
    default: openapi.yaml
  OPENAPI_PATH:
    description: 'Path to the OpenAPI file'
    required: false
    default: app%2Fopenapi

runs:
  using: 'composite'
  steps:
  # Checkout generator repo
  - uses: actions/checkout@v2
    with:
      repository: InformaticsMatters/openapi-js-client-generator
      branch: main
  - uses: actions/checkout@v2
    with:
      path: "./client"
  # We need Node 16
  - uses: actions/setup-node@v2
    with:
      node-version: 16
      cache: 'npm'
  # Get the openapi.yaml file
  - run: |
      curl -H "Private-Token: ${GITLAB_API_TOKEN}" ${GITLAB_API}/${GITLAB_PROJECT}/repository/files/${OPENAPI_PATH}%2F${OPENAPI_FILE}/raw?ref=${CI_COMMIT_TAG} --output ${OPENAPI_FILE}
      tail ${OPENAPI_FILE}
      cat ${OPENAPI_FILE} | wc -l
    shell: bash
  - run: npm i -g json
    shell: bash
  - run: cat package.json client/package.override.json | json --deep-merge | tee package.json
    shell: bash
  - run: |
      sed -i s/'ORVAL_API_NAME'/'"'${API_NAME}'"'/ orval.config.cjs
      sed -i s/'API_TARGET_NAME'/''${API_TARGET_NAME}''/ orval.config.cjs
    shell: bash
  - run: npm ci
    shell: bash
  - run: |
      npm run orval
      npx tsup
      ls dist/
      node setup-entrypoints.js
    shell: bash

