name: 'OpenAPI JS Client Generator'
description: 'Generates and publishes a package and documentation from a source openapi.yaml file.'
author: 'Oliver Dudgeon'

inputs:
  CI_COMMIT_TAG:
    description: "CI Tag to use as the package version"
    required: true

runs:
  using: 'composite'
  steps:
  - uses: actions/setup-node@v2
    env:
        NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
    with:
      node-version: 16
      registry-url: 'https://registry.npmjs.org'
  - run: |
      cat package.json package.release.json | json --deep-merge | tee dist/package.json
    shell: bash
  - run: |
      cp client/README.md dist/README.md
      cp client/LICENSE dist/LICENSE
      cd dist
      head package.json
      npx -y release-it --npm.skipChecks --ci ${{ inputs.CI_COMMIT_TAG}}
    shell: bash
    env:
      GITHUB_TOKEN : ${{ env.GITHUB_TOKEN }}
