name: 'OpenAPI JS Client Generator'
description: 'Generates and publishes a package and documentation from a source openapi.yaml file.'
author: 'Oliver Dudgeon'

inputs:
  CI_COMMIT_TAG:
    description: "CI Tag to use as the package version"
    required: true

runs:
  using: 'composite'
  steps:
  - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    env:
        NPM_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
    shell: bash
  - run: |
      cat package.json package.release.json | json --deep-merge | tee dist/package.json
    shell: bash
  - name: git config
    shell: bash
    run: |
      git config user.name "${GITHUB_ACTOR}"
      git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
  - run: |
      cp client/README.md dist/README.md
      cp client/LICENSE dist/LICENSE
      mv dist client
      cd client/dist
      head package.json
      npx -y release-it --npm.skipChecks --ci ${{ inputs.CI_COMMIT_TAG}}
    shell: bash
    env:
      GITHUB_TOKEN : ${{ env.GITHUB_TOKEN }}
